'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Türkçe ve İngilizce çeviriler
const translations: Record<Language, Record<string, string>> = {
  tr: {
    // Premium engel modalı
    'premiumBlock.title': 'Belge yükle, erişim kazan!',
    'premiumBlock.desc1': 'Sadece bir belge yükleyerek',
    'premiumBlock.desc2': '3 farklı kaynağa erişim',
    'premiumBlock.desc3': 'ödülü kazanabilirsin. Ne kadar çok paylaşırsan, o kadar çok kaynağa erişirsin!',
    'premiumBlock.uploadBtn': 'Belge Yükle',
    'premiumBlock.shareToUnlock': 'Açmak için paylaş',
    'premiumBlock.alreadyUser': 'Zaten üye misin?',
    'premiumBlock.login': 'Giriş yap',
    // Takvim
    'calendar.today': 'Bugün',
    'calendar.previous': 'Önceki',
    'calendar.next': 'Sonraki',
    'calendar.month': 'Ay',
    'calendar.week': 'Hafta',
    'calendar.day': 'Gün',
    'calendar.agenda': 'Ajanda',
    'calendar.date': 'Tarih',
    'calendar.time': 'Saat',
    'calendar.event': 'Etkinlik',
    'calendar.more': 'daha...',
    'calendar.noEventsInRange': 'Bu aralıkta ders bulunmuyor',
    // Kaynak formatları
    'resourceFormat.pdf': 'PDF',
    'resourceFormat.doc': 'DOC/DOCX',
    'resourceFormat.ppt': 'PPT/PPTX',
    'resourceFormat.jpg': 'JPG',
    'resourceFormat.jpeg': 'JPEG',
    'resourceFormat.png': 'PNG',
    'resourceFormat.xls': 'XLS/XLSX',
    'resourceFormat.video': 'Video',
    'resourceFormat.audio': 'Ses',
    'resourceFormat.image': 'Resim',
    'resourceFormat.link': 'Link',
    'resourceFormat.other': 'Diğer',
    // Kaynak kategorileri
    'general.selectOption': 'Seçiniz',
    'resourceCategory.notes': 'Ders Notları',
    'resourceCategory.books': 'Kitaplar',
    'resourceCategory.articles': 'Makaleler',
    'resourceCategory.videos': 'Videolar',
    'resourceCategory.presentations': 'Sunumlar',
    'resourceCategory.examQuestions': 'Sınav Soruları',
    'resourceCategory.projects': 'Projeler',
    'resourceCategory.other': 'Diğer',
    // Akademik seviyeler
    'academicLevel.associate': 'Ön Lisans',
    'academicLevel.bachelor': 'Lisans',
    'academicLevel.master': 'Yüksek Lisans',
    'academicLevel.phd': 'Doktora',
    // Navbar
    'nav.home': 'Ana Sayfa',
    'nav.listings': 'İlanlar',
    'nav.lessons': 'Derslerim',
    'nav.createListing': 'İlan Ver',
    'nav.createLesson': 'Ders Oluştur',
    'nav.login': 'Giriş Yap',
    'nav.register': 'Kayıt Ol',
    'nav.profile': 'Profilim',
    'nav.messages': 'Mesajlarım',
    'nav.myLessons': 'Derslerim',
    'nav.myListings': 'İlanlarım',
    'nav.logout': 'Çıkış Yap',
    'nav.instructors': 'Eğitmenler',
    'nav.resources': 'Kaynaklar',
    'nav.contact': 'İletişim',
    'nav.about': 'Hakkımızda',
    'nav.faq': 'Sıkça Sorulan Sorular',
    'nav.blog': 'Blog',
    'nav.language': 'Dil',
    'nav.notifications': 'Bildirimler',
    
    // Genel
    'general.search': 'Ara',
    'general.filter': 'Filtrele',
    'general.filters': 'Filtreler',
    'general.searchResources': 'Kaynak Ara',
    'general.filterResources': 'Kaynakları Filtrele',
    'general.allResources': 'Tüm Kaynaklar',
    'general.allUniversities': 'Tüm Üniversiteler',
    'general.shareResource': 'Kaynak Paylaş',
    'general.resourceTitle': 'Kaynak Başlığı',
    'general.resourceDescription': 'Kaynak Açıklaması',
    'general.resourceType': 'Kaynak Türü',
    'general.resourceLink': 'Kaynak Bağlantısı',
    'general.resourceFile': 'Kaynak Dosyası',
    'general.uploadResource': 'Kaynak Yükle',
    'general.resourceCategory': 'Kategori',
    'general.resourceSubject': 'Konu',
    'general.resourceLevel': 'Seviye',
    'general.resourceLanguage': 'Dil',
    'general.resourceFormat': 'Format',
    'general.fileUploadClickOrDrag': 'Dosya yüklemek için tıklayın veya sürükleyip bırakın',
    'general.fileUploadFormats': 'PDF, DOC, PPT, XLS, MP4, MP3, JPG, PNG (Max 50MB)',
    'general.tagsPlaceholder': 'matematik, calculus, türev, integral',
    'general.resourceAuthor': 'Yazar',
    'general.resourceDate': 'Tarih',
    'general.resourceSize': 'Boyut',
    'general.resourceDownload': 'İndir',
    'general.resourceView': 'Görüntüle',
    'general.resourceShare': 'Paylaş',
    'general.resourceSave': 'Kaydet',
    'general.resourceDelete': 'Sil',
    'general.resourceEdit': 'Düzenle',
    'general.resourceReport': 'Bildir',
    'general.resourceLike': 'Beğen',
    'general.resourceComment': 'Yorum Yap',
    'general.resourceComments': 'Yorumlar',
    'general.resourceRating': 'Değerlendirme',
    'general.resourceViews': 'Görüntülenme',
    'general.resourceDownloads': 'İndirme',
    'general.resourceShares': 'Paylaşım',
    'general.resourceLikes': 'Beğeni',
    'general.resourceDislikes': 'Beğenmeme',
    'general.resourceFavorites': 'Favoriler',
    'general.resourceBookmarks': 'Yer İmleri',
    'general.preview': 'Önizle',
    'general.downloadFile': 'Dosyayı İndir',
    'general.resourceRelated': 'İlgili Kaynaklar',
    'general.resourcePopular': 'Popüler Kaynaklar',
    'general.resourceRecent': 'Son Eklenen Kaynaklar',
    'general.resourceFeatured': 'Öne Çıkan Kaynaklar',
    'general.resourceRecommended': 'Önerilen Kaynaklar',
    'general.resourceTrending': 'Trend Kaynaklar',
    'general.resourceNew': 'Yeni Kaynaklar',
    'general.resourceMostViewed': 'En Çok Görüntülenen',
    'general.resourceMostDownloaded': 'En Çok İndirilen',
    'general.resourceMostShared': 'En Çok Paylaşılan',
    'general.resourceMostLiked': 'En Çok Beğenilen',
    'general.resourceMostCommented': 'En Çok Yorum Yapılan',
    'general.resourceMostRated': 'En Çok Değerlendirilen',
    'general.resourceHighestRated': 'En Yüksek Puanlı',
    'general.resourceLowestRated': 'En Düşük Puanlı',
    'general.resourceCategories': 'Kategoriler',
    'general.resourceSubjects': 'Konular',
    'general.resourceLevels': 'Seviyeler',
    'general.resourceLanguages': 'Diller',
    'general.resourceFormats': 'Formatlar',
    'general.resourceAuthors': 'Yazarlar',
    'general.resourceDates': 'Tarihler',
    'general.resourceSizes': 'Boyutlar',
    'general.resourceTags': 'Etiketler',
    'general.resourceKeywords': 'Anahtar Kelimeler',
    'general.resourceSearch': 'Kaynak Arama',
    'general.resourceAdvancedSearch': 'Gelişmiş Arama',
    'general.resourceSearchResults': 'Arama Sonuçları',
    'general.resourceSearchNoResults': 'Arama Sonucu Bulunamadı',
    'general.resourceSearchTips': 'Arama İpuçları',
    'general.resourceSearchFilters': 'Arama Filtreleri',
    'general.resourceSearchSort': 'Sıralama',
    'general.resourceSearchSortBy': 'Sıralama Kriteri',
    'general.resourceSearchSortOrder': 'Sıralama Düzeni',
    'general.resourceSearchSortAsc': 'Artan',
    'general.resourceSearchSortDesc': 'Azalan',
    'general.price': 'Fiyat',
    'general.duration': 'Süre',
    'general.method': 'Yöntem',
    'general.submit': 'Gönder',
    'general.cancel': 'İptal',
    'general.save': 'Kaydet',
    'general.edit': 'Düzenle',
    'general.delete': 'Sil',
    'general.back': 'Geri',
    'general.next': 'İleri',
    'general.finish': 'Bitir',
    'general.loading': 'Yükleniyor...',
    'general.error': 'Hata',
    'general.success': 'Başarılı',
    'general.noResults': 'Sonuç bulunamadı',
    'general.clearFilters': 'Filtreleri Temizle',
    'general.showAll': 'Tümünü Göster',
    'general.hourlyRate': 'Saatlik Ücret',
    'general.lessonFrequency': 'Ders Sıklığı',
    'frequency.daily': 'Günlük',
    'frequency.weekly': 'Haftalık',
    'frequency.monthly': 'Aylık',
    'frequency.flexible': 'Esnek',
    'general.lessonMethod': 'Ders Yöntemi',
    'general.instructor': 'Eğitmen',
    'general.university': 'Üniversite',
    'general.department': 'Bölüm',
    'general.academicLevel': 'Akademik Seviye',
    'general.expertise': 'Uzmanlık Alanı',
    'general.description': 'Açıklama',
    'general.contactTeacher': 'Eğitmen ile İletişime Geç',
    'general.bookAppointment': 'Randevu Al',
    'general.sendMessage': 'Mesaj Gönder',
    'general.goBack': 'Geri Dön',
    'general.backToListings': 'İlanlara Geri Dön',
    'general.openListings': 'Açık İlanlar',
    'general.showAllListings': 'Tüm İlanları Göster',
    'general.processing': 'İşleniyor...',
    'general.publish': 'Yayınla',
    'general.accessDenied': 'Erişim Engellendi',
    'general.accessDeniedMessage': 'Bu sayfaya erişmek için eğitmen hesabıyla giriş yapmanız gerekmektedir.',
    'general.goToHomepage': 'Ana Sayfaya Dön',
    'general.online': 'Online',
    'general.faceToFace': 'Yüz Yüze',
    'general.hybrid': 'Hibrit (Online + Yüz Yüze)',
    'general.createListingTitle': 'Yeni İlan Oluştur',
    'listings.universityListings': 'Üniversite İlanları',
    'listings.exploreTeacherLessons': 'Eğitmen Derslerini Keşfet',
    'general.listingTitle': 'İlan Başlığı',
    'general.listingTitlePlaceholder': 'Örn: Python Programlama Dersi',
    'general.listingDescription': 'Detaylı Açıklama',
    'general.listingDescriptionPlaceholder': 'Ders içeriği ve kendiniz hakkında bilgi verin...',
    'general.hourlyPrice': 'Ders Ücreti (₺/Saat)',
    'general.hours': 'Saat',
    'general.lessonDurationHours': 'Ders Süresi (Saat)',
    'general.hourlyPricePlaceholder': 'Örn: 150',
    'general.instructorFrom': 'Dersi Aldığınız Eğitmen',
    'general.instructorFromPlaceholder': 'Örn: Ankara Üniversitesi, Prof. Dr. Ahmet Yılmaz',
    'general.publishListing': 'İlanı Yayınla',
    'general.listingCreated': 'İlanınız başarıyla oluşturuldu!',
    'general.searchPlaceholder': 'İlan ara...',
    'general.filterOptions': 'Filtreleme Seçenekleri',
    'general.sort': 'Sıralama',
    'general.newest': 'En Yeni',
    'general.oldest': 'En Eski',
    'general.priceAsc': 'Fiyat (Artan)',
    'general.priceDesc': 'Fiyat (Azalan)',
    'general.minPrice': 'Minimum Ücret (₺)',
    'general.maxPrice': 'Maksimum Ücret (₺)',
    'general.allMethods': 'Tüm yöntemler',
    'general.minPricePlaceholder': 'Minimum fiyat',
    'general.maxPricePlaceholder': 'Maksimum fiyat',
    'general.resultsFound': 'ilan bulundu',
    'general.notSpecified': 'Belirtilmemiş',
    'general.unknown': 'Bilinmiyor',
    'general.noResultsFound': 'Arama Sonuçları Bulunamadı',
    'general. resourceSearchNoResults': 'Kaynak Bulunamadı',
    'general.noResultsForSearch': 'Aradığınız kriterlere uygun sonuç bulunamadı.',
    'general.downloadStarted': 'İndirme başladı.',
    'general.downloadError': 'İndirme sırasında bir hata oluştu. Lütfen tekrar deneyin.',
    'general.fileNotFound': 'Dosya bulunamadı. Bu kaynak için indirilebilir bir dosya yok.',
    'general.noListingsYet': 'Henüz İlan Bulunmuyor',
    'general.listingsWillAppear': 'Üniversitenizdeki eğitmenler ilan verdikçe burada görüntülenecektir.',
    'general.tryAgain': 'Yeniden Dene',
    'general.listingDetails': 'İlan Detayları',
    'general.lessonDetails': 'Ders Detayları',
    'general.teacherInfo': 'Eğitmen Bilgisi',
    'general.additionalInfo': 'Ek Bilgiler',
    'general.allListings': 'Tüm İlanları',
    'general.hour': 'Saat',
    'general.viewDetails': 'Detayları Gör',
    'general.locale': 'tr',
    'general.currency': 'TL',
    
    // Anasayfa
    'home.mainTitle': 'İhtiyacına en uygun öğrencileri bul, hemen öğrenmeye başla!',
    'home.showAllUniversities': 'Tüm üniversiteleri göster',
    'home.allUniversities': 'Tüm Üniversiteler',
    'home.selectUniversity': 'Üniversitenizi seçin...',
    'home.description': 'Kavunla, aynı üniversite öğrencilerini bir araya getiren yeni nesil bir eğitim platformudur.',
    'home.exploreCourses': 'Kursları Keşfet',
    'home.howToContinue': 'Nasıl devam etmek istersiniz?',
    'home.continueAsStudent': 'Öğrenci Olarak Devam Et',
    'home.continueAsInstructor': 'Eğitmen Olarak Devam Et',
    
    // Profil sayfası
    'profile.profileInfo': 'Profil Bilgileri',
    'profile.editProfile': 'Profili Düzenle',
    'profile.fullName': 'Ad Soyad',
    'profile.email': 'E-posta',
    'profile.university': 'Üniversite',
    'profile.role': 'Rol',
    'profile.department': 'Okudğu Bölüm',
    'profile.class': 'Sınıf',
    'profile.updateSuccess': 'Profil başarıyla güncellendi.',
    'profile.accountStatus': 'Hesap Durumu',
    'profile.verified': 'Doğrulanmış',
    'profile.unverified': 'Doğrulanmamış',
    'profile.preparatory': 'Hazırlık',
    'profile.firstYear': '1. Sınıf',
    'profile.secondYear': '2. Sınıf',
    'profile.thirdYear': '3. Sınıf',
    'profile.fourthYear': '4. Sınıf',
    'profile.fifthYear': '5. Sınıf',
    'profile.sixthYear': '6. Sınıf',
    'profile.graduate': 'Mezun',
    
    // Mesajlaşma sayfası
    'messages.myMessages': 'Mesajlarım',
    'messages.conversations': 'Konuşmalarım',
    'messages.startMessaging': 'Mesajlaşmaya Başlayın',
    'messages.selectConversation': 'Sol taraftan bir konuşma seçin veya eğitmen profillerini ziyaret ederek yeni bir mesajlaşma başlatın.',
    'messages.loginRequired': 'Mesajlarınızı görmek için giriş yapmalısınız',
    'messages.noMessages': 'Henüz mesajınız yok',
    'messages.visitInstructors': 'Eğitmenlerle mesajlaşmaya başlamak için profillerini ziyaret edebilirsiniz.',
    'messages.exploreInstructors': 'Eğitmenleri Keşfet',
    
    // İlanlarım sayfası
    'myListings.myListings': 'İlanlarım',
    'myListings.addNewListing': 'Yeni İlan Ekle',
    'myListings.noListingsYet': 'Henüz hiç ilan oluşturmadınız.',
    'myListings.addYourFirstListing': 'İlk İlanınızı Ekleyin',
    
    // Kimlik doğrulama sayfaları
    'auth.login': 'Giriş Yap',
    'auth.register': 'Kayıt Ol',
    'auth.noAccount': 'Hesabınız yok mu?',
    'auth.haveAccount': 'Zaten hesabınız var mı?',
    'auth.email': 'Email',
    'auth.password': 'Şifre',
    'auth.rememberMe': 'Beni Hatırla',
    'auth.forgotPassword': 'Şifremi Unuttum',
    'auth.fullName': 'Ad Soyad',
    'auth.confirmPassword': 'Şifre Tekrar',
    'auth.role': 'Rol',
    'auth.student': 'Öğrenci',
    'auth.instructor': 'Eğitmen',
    'auth.university': 'Üniversite',

    // Eğitmenler sayfası
    'instructors.title': 'Eğitmenlerimiz',
    'instructors.universityDesc': '{university} üniversitesindeki eğitmenlerimizle tanışın ve ihtiyacınıza en uygun eğitmeni seçin.',
    'instructors.generalDesc': 'Alanında uzman eğitmenlerimizle tanışın ve ihtiyacınıza en uygun eğitmeni seçin.',
    'instructors.searchPlaceholder': 'Eğitmen ara...',
    'instructors.departmentsTitle': 'Uzmanlık Alanları',
    'instructors.noMatch': 'Aradığınız kriterlere uygun eğitmen bulunamadı.',
    'instructors.noInstructors': 'Henüz hiç eğitmen bulunmuyor.',
    'instructors.tryDifferentSearch': 'Farklı arama kriterleri deneyebilirsiniz.',
    'instructors.role': 'Eğitmen',
    'instructors.generalInstructor': 'Genel Eğitmen',
    'instructors.experience': '3+ Yıl Deneyim',
    'instructors.rating': '4.8/5 Puan',
    'instructors.expertise': 'Genel Eğitmen',

    // Bölüm isimleri
    'departments.computer': 'Bilgisayar Mühendisliği',
    'departments.dentistry': 'Diş Hekimliği',
    'departments.medicine': 'Tıp',
    'departments.law': 'Hukuk',
    'departments.mechanical': 'Makine Mühendisliği',
    'departments.electrical': 'Elektrik-Elektronik Mühendisliği',
    'departments.business': 'İşletme',
    'departments.psychology': 'Psikoloji',
    'departments.architecture': 'Mimarlık',
    'departments.industrial': 'Endüstri Mühendisliği',
    'departments.civil': 'İnşaat Mühendisliği',
    'departments.software': 'Yazılım Mühendisliği',
    'general.allDepartments': 'Tüm Bölümler',
    'general.allRatings': 'Tüm Puanlar',
    'auth.selectUniversity': 'Üniversitenizi seçin...',
    'auth.department': 'Bölümünüz',
    'auth.departmentPlaceholder': 'Bölümünüzü yazınız...',
    'auth.class': 'Sınıfınız',
    'auth.selectClass': 'Seçiniz',
    'auth.passwordRequirement': 'En az 8 karakter olmalıdır',
    'auth.loggingIn': 'Giriş Yapılıyor...',
    'auth.registering': 'Kayıt Yapılıyor...',
    'auth.otherSignInOptions': 'Diğer giriş seçenekleri',
    'auth.termsAgreement': 'Kayıt olarak, kabul etmiş sayılırsınız:',
    'auth.termsOfUse': 'Kullanım Koşulları',
    'auth.and': 've',
    'auth.privacyPolicy': 'Gizlilik Politikası',
    
    // Derslerim sayfası
    'lessons.myLessons': 'Derslerim',
    'lessons.teacherManageLessons': 'Tüm derslerinizi bu sayfadan yönetebilirsiniz.',
    'lessons.studentViewLessons': 'Kayıtlı olduğunuz tüm dersleri bu sayfadan görüntüleyebilirsiniz.',
    'lessons.totalLessons': 'Toplam Ders',
    'lessons.plannedLessons': 'Planlanan Dersler',
    'lessons.completedLessons': 'Tamamlanan Dersler',
    'lessons.cancelledLessons': 'İptal Edilen Dersler',
    'lessons.lessonCalendar': 'Ders Takvimi',
    'lessons.status': 'Durum',
    'lessons.start': 'Başlangıç',
    'lessons.end': 'Bitiş',
    'lessons.student': 'Öğrenci',
    'lessons.instructor': 'Eğitmen',
    'lessons.price': 'Ücret',
    'lessons.completeLesson': 'Dersi Tamamla',
    'lessons.cancelLesson': 'Dersi İptal Et',
    'lessons.viewLessonDetails': 'Ders Detaylarını Görüntüle',
    'lessons.statusOpen': 'Açık',
    'lessons.statusScheduled': 'Planlandı',
    'lessons.statusCompleted': 'Tamamlandı',
    'lessons.statusCancelled': 'İptal Edildi',
    'lessons.details': 'Ders Detayları',
    'lessons.createdAt': 'Oluşturulma Tarihi',
    'lessons.minute': 'dakika',
    'lessons.noDate': 'Tarih belirtilmemiş',
    'lessons.notFound': 'Ders Bulunamadı',
    'lessons.notFoundDesc': 'Görüntülemeye çalıştığınız ders bulunamadı veya erişim izniniz yok.',
    'lessons.completedAt': 'Tamamlandı',
    'lessons.studentInfo': 'Öğrenci Bilgileri',
    'lessons.teacherInfo': 'Eğitmen Bilgileri',
    'lessons.paymentStatus': 'Ödeme Durumu',
    'lessons.notPaid': 'Bu ders için henüz ödeme yapılmamış.',
    'lessons.payNow': 'Ödeme Yap',
    'lessons.paid': 'Ödeme tamamlandı',
    'messages.sendMessage': 'Mesaj Gönder',
    'lessons.student ': 'Öğrenci',
    'lessons.teacher': 'Eğitmen',
    'general.noName': 'İsim belirtilmemiş',
    'general.noEmail': 'E-posta belirtilmemiş',

    // Loglar ve hatalar
    'logs.userNotLoggedIn': 'Kullanıcı girişi yapılmamış, yönlendiriliyor...',
    'logs.listingCreationError': 'İlan oluşturulurken hata:',
    'logs.previewUpdateError': 'Önizleme sayısı güncellenirken hata oluştu',
    'logs.fetchingLessonStats': 'Kullanıcı girişi yapılmış, ders istatistikleri getiriliyor...',
    'logs.sendingApiRequest': 'API isteği gönderiliyor:',
    'logs.tokenAvailable': 'Token mevcut:',
    'logs.lessonStatsReceived': 'Ders istatistikleri alındı:',
    'errors.userInfoNotFound': 'Kullanıcı bilgisi bulunamadı',
    'errors.apiError': 'API hatası:',
    'errors.errorDetails': 'Hata detayı:',
    'errors.fetchingLessonStats': 'Ders istatistikleri alınırken bir hata oluştu',
    'errors.fetchingLessonStatsError': 'Ders istatistikleri getirme hatası:',
    'errors.serverError': 'Sunucu hatası',
    'errors.universityNotFound': 'Üniversite bilgisi bulunamadı',
    'errors.fetchingListings': 'İlanlar getirilirken bir hata oluştu',
    'errors.tokenNotFound': 'Token bulunamadı',
    'errors.sessionExpired': 'Oturumunuz sonlanmış görünüyor. Lütfen tekrar giriş yapın.',
    'errors.unknownError': 'Bilinmeyen hata',
    'errors.httpError': 'HTTP hata: {status}',
    'errors.loadingConversations': 'Konuşmalar yüklenirken hata oluştu',
    'errors.loadingConversationsDetail': 'Konuşmalar yüklenirken bir hata oluştu:',
    'errors.fetchingUserDetails': 'Kullanıcı detayları alınırken hata oluştu',
    'errors.titleRequired': 'Lütfen bir başlık girin',
    'errors.descriptionRequired': 'Lütfen bir açıklama girin',
    'errors.priceRequired': 'Lütfen ücret bilgisi girin',
    'errors.durationRequired': 'Lütfen süre bilgisi girin',
    'errors.userIdNotFound': 'Kullanıcı kimliği bulunamadı. Lütfen tekrar giriş yapın.',
    'errors.sessionNotFound': 'Oturum bilgisi bulunamadı. Lütfen tekrar giriş yapın.',
    'errors.listingCreationError': 'İlan oluşturulurken bir hata oluştu',
    'errors.listingCreationErrorTryAgain': 'İlan oluşturulurken bir hata oluştu. Lütfen daha sonra tekrar deneyin.',
    'errors.loginRequired': 'Bu kaynağı indirebilmek için giriş yapmalısınız.',
    'errors.noDownloadPermission': 'Bu kaynağı indirmek için yetkiniz bulunmamaktadır.',
    'errors.invalidUniversity': 'Lütfen geçerli bir üniversite seçin',
    'errors.invalidDepartment': 'Lütfen geçerli bir bölüm seçin',
    
    // Footer
    'footer.platformDescription': 'Kavunla, öğrencileri eğitmenlerle buluşturan ve eğitimin geleceğini şekillendiren platform.',
    'footer.quickLinks': 'Hızlı Bağlantılar',
    'footer.legal': 'Yasal',
    'footer.termsOfUse': 'Kullanım Koşulları',
    'footer.privacyPolicy': 'Gizlilik Politikası',
    'footer.cookiePolicy': 'Çerez Politikası',
    'footer.pdpl': 'KVKK',
    'footer.contact': 'İletişim',
    'footer.allRightsReserved': 'Tüm hakları saklıdır.',
    'footer.support': 'Destek',
    'footer.security': 'Güvenlik',
    'footer.notification': 'Bildirim',
  },
  en: {
    // Premium block modal
    'premiumBlock.title': 'Upload a document, get instant access!',
    'premiumBlock.desc1': 'Upload just one document to',
    'premiumBlock.desc2': 'unlock access to 3 resources',
    'premiumBlock.desc3': 'as a reward. The more you share, the more you unlock!',
    'premiumBlock.uploadBtn': 'Upload Document',
    'premiumBlock.shareToUnlock': 'Share to unlock',
    'premiumBlock.alreadyUser': 'Already a user?',
    'premiumBlock.login': 'Log in',
    // Instructors page
    'instructors.title': 'Our Instructors',
    'instructors.universityDesc': 'Meet the instructors at {university} University and choose the one that best suits your needs.',
    'instructors.generalDesc': 'Meet our expert instructors and choose the one that best suits your needs.',
    'instructors.searchPlaceholder': 'Search instructor...',
    'instructors.departmentsTitle': 'Expertise Areas',
    'instructors.noMatch': 'No instructor found matching your criteria.',
    'instructors.noInstructors': 'No instructors yet.',
    'instructors.tryDifferentSearch': 'You can try different search criteria.',
    'instructors.role': 'Instructor',
    'instructors.generalInstructor': 'General Instructor',
    'instructors.experience': '3+ Years Experience',
    'instructors.rating': '4.8/5 Rating',
    'instructors.expertise': 'General Instructor',

    // Department names
    'departments.computer': 'Computer Engineering',
    'departments.dentistry': 'Dentistry',
    'departments.medicine': 'Medicine',
    'departments.law': 'Law',
    'departments.mechanical': 'Mechanical Engineering',
    'departments.electrical': 'Electrical-Electronics Engineering',
    'departments.business': 'Business',
    'departments.psychology': 'Psychology',
    'departments.architecture': 'Architecture',
    'departments.industrial': 'Industrial Engineering',
    'departments.civil': 'Civil Engineering',
    'departments.software': 'Software Engineering',
    'general.allDepartments': 'All Departments',
    'general.allRatings': 'All Ratings',
    // Calendar
    'calendar.today': 'Today',
    'calendar.previous': 'Previous',
    'calendar.next': 'Next',
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.day': 'Day',
    'calendar.agenda': 'Agenda',
    'calendar.date': 'Date',
    'calendar.time': 'Time',
    'calendar.event': 'Event',
    'calendar.more': 'more...',
    'calendar.noEventsInRange': 'No lessons in this range',
    // Resource formats
    'resourceFormat.pdf': 'PDF',
    'resourceFormat.doc': 'DOC/DOCX',
    'resourceFormat.ppt': 'PPT/PPTX',
    'resourceFormat.jpg': 'JPG',
    'resourceFormat.jpeg': 'JPEG',
    'resourceFormat.png': 'PNG',
    'resourceFormat.xls': 'XLS/XLSX',
    'resourceFormat.video': 'Video',
    'resourceFormat.audio': 'Audio',
    'resourceFormat.image': 'Image',
    'resourceFormat.link': 'Link',
    'resourceFormat.other': 'Other',
    // Resource categories
    'general.selectOption': 'Select',
    'resourceCategory.notes': 'Lecture Notes',
    'resourceCategory.books': 'Books',
    'resourceCategory.articles': 'Articles',
    'resourceCategory.videos': 'Videos',
    'resourceCategory.presentations': 'Presentations',
    'resourceCategory.examQuestions': 'Exam Questions',
    'resourceCategory.projects': 'Projects',
    'resourceCategory.other': 'Other',
    // Academic levels
    'academicLevel.associate': 'Associate Degree',
    'academicLevel.bachelor': 'Bachelor',
    'academicLevel.master': 'Master',
    'academicLevel.phd': 'PhD',
    // Navbar
    'nav.home': 'Home',
    'nav.listings': 'Listings',
    'nav.lessons': 'My Lessons',
    'nav.createListing': 'Create Listing',
    'nav.createLesson': 'Create Lesson',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.profile': 'My Profile',
    'nav.messages': 'My Messages',
    'nav.myLessons': 'My Lessons',
    'nav.myListings': 'My Listings',
    'nav.logout': 'Logout',
    'nav.instructors': 'Instructors',
    'nav.resources': 'Resources',
    'nav.contact': 'Contact',
    'nav.about': 'About Us',
    'nav.faq': 'FAQ',
    'nav.blog': 'Blog',
    'nav.language': 'Language',
    'nav.notifications': 'Notifications',
    
    // General
    'home.description': 'Kavunla is a next-generation education platform that brings together students from the same university.',
    'general.search': 'Search',
    'general.filter': 'Filter',
    'general.filters': 'Filters',
    'general.searchResources': 'Search Resources',
    'general.filterResources': 'Filter Resources',
    'general.allResources': 'All Resources',
    'general.allUniversities': 'All Universities',
    'general.shareResource': 'Share Resource',
    'general.resourceTitle': 'Resource Title',
    'general.resourceDescription': 'Resource Description',
    'general.resourceType': 'Resource Type',
    'general.resourceLink': 'Resource Link',
    'general.resourceFile': 'Resource File',
    'general.uploadResource': 'Upload Resource',
    'general.resourceCategory': 'Category',
    'general.resourceSubject': 'Subject',
    'general.resourceLevel': 'Level',
    'general.resourceLanguage': 'Language',
    'general.resourceFormat': 'Format',
    'general.fileUploadClickOrDrag': 'Click or drag to upload',
    'general.fileUploadFormats': 'PDF, DOC, PPT, XLS, MP4, MP3, JPG, PNG (Max 50MB)',
    'general.tagsPlaceholder': 'matematik, calculus, türev, integral',
    'general.resourceAuthor': 'Author',
    'general.resourceDate': 'Date',
    'general.resourceSize': 'Size',
    'general.resourceDownload': 'Download',
    'general.resourceView': 'View',
    'general.resourceShare': 'Share',
    'general.resourceSave': 'Save',
    'general.resourceDelete': 'Delete',
    'general.resourceEdit': 'Edit',
    'general.resourceReport': 'Report',
    'general.resourceLike': 'Like',
    'general.resourceComment': 'Comment',
    'general.resourceComments': 'Comments',
    'general.resourceRating': 'Rating',
    'general.resourceViews': 'Views',
    'general.resourceDownloads': 'Downloads',
    'general.resourceShares': 'Shares',
    'general.resourceLikes': 'Likes',
    'general.resourceDislikes': 'Dislikes',
    'general.resourceFavorites': 'Favorites',
    'general.resourceBookmarks': 'Bookmarks',
    'general.preview': 'Preview',
    'general.downloadFile': 'Download File',
    'general.resourceRelated': 'Related Resources',
    'general.resourcePopular': 'Popular Resources',
    'general.resourceRecent': 'Recent Resources',
    'general.resourceFeatured': 'Featured Resources',
    'general.resourceRecommended': 'Recommended Resources',
    'general.resourceTrending': 'Trending Resources',
    'general.resourceNew': 'New Resources',
    'general.resourceMostViewed': 'Most Viewed',
    'general.resourceMostDownloaded': 'Most Downloaded',
    'general.resourceMostShared': 'Most Shared',
    'general.resourceMostLiked': 'Most Liked',
    'general.resourceMostCommented': 'Most Commented',
    'general.resourceMostRated': 'Most Rated',
    'general.resourceHighestRated': 'Highest Rated',
    'general.resourceLowestRated': 'Lowest Rated',
    'general.resourceCategories': 'Categories',
    'general.resourceSubjects': 'Subjects',
    'general.resourceLevels': 'Levels',
    'general.resourceLanguages': 'Languages',
    'general.resourceFormats': 'Formats',
    'general.resourceAuthors': 'Authors',
    'general.resourceDates': 'Dates',
    'general.resourceSizes': 'Sizes',
    'general.resourceTags': 'Tags',
    'general.resourceKeywords': 'Keywords',
    'general.resourceSearch': 'Resource Search',
    'general.resourceAdvancedSearch': 'Advanced Search',
    'general.resourceSearchResults': 'Search Results',
    'general.resourceSearchNoResults': 'Resource Not Found',
    'general.resourceSearchTips': 'Search Tips',
    'general.resourceSearchFilters': 'Search Filters',
    'general.resourceSearchSort': 'Sort',
    'general.resourceSearchSortBy': 'Sort By',
    'general.resourceSearchSortOrder': 'Sort Order',
    'general.resourceSearchSortAsc': 'Ascending',
    'general.resourceSearchSortDesc': 'Descending',
    'general.price': 'Price',
    'general.duration': 'Duration',
    'general.method': 'Method',
    'general.submit': 'Submit',
    'general.cancel': 'Cancel',
    'general.save': 'Save',
    'general.edit': 'Edit',
    'general.delete': 'Delete',
    'general.back': 'Back',
    'general.next': 'Next',
    'general.finish': 'Finish',
    'general.loading': 'Loading...',
    'general.error': 'Error',
    'general.success': 'Success',
    'general.noResults': 'No results found',
    'general.clearFilters': 'Clear Filters',
    'general.showAll': 'Show All',
    'general.hourlyRate': 'Hourly Rate',
    'general.lessonFrequency': 'Lesson Frequency',
    'frequency.daily': 'Daily',
    'frequency.weekly': 'Weekly',
    'frequency.monthly': 'Monthly',
    'frequency.flexible': 'Flexible',
    'general.lessonMethod': 'Lesson Method',
    'general.instructor': 'Instructor',
    'general.university': 'University',
    'general.department': 'Department',
    'general.academicLevel': 'Academic Level',
    'general.expertise': 'Expertise',
    'general.description': 'Description',
    'general.contactTeacher': 'Contact Teacher',
    'general.bookAppointment': 'Book Appointment',
    'general.sendMessage': 'Send Message',
    'general.goBack': 'Go Back',
    'general.backToListings': 'Back to Listings',
    'general.openListings': 'Open Listings',
    'general.showAllListings': 'Show All Listings',
    'general.processing': 'Processing...',
    'general.publish': 'Publish',
    'general.accessDenied': 'Access Denied',
    'general.accessDeniedMessage': 'You need to login with an instructor account to access this page.',
    'general.goToHomepage': 'Go to Homepage',
    'general.online': 'Online',
    'general.faceToFace': 'Face to Face',
    'general.hybrid': 'Hybrid (Online + Face to Face)',
    'general.createListingTitle': 'Create New Listing',
    'listings.universityListings': 'University Listings',
    'listings.exploreTeacherLessons': 'Explore Teacher Lessons',
    'general.listingTitle': 'Listing Title',
    'general.listingTitlePlaceholder': 'E.g.: Python Programming Course',
    'general.listingDescription': 'Listing Description',
    'general.listingDescriptionPlaceholder': 'Provide information about the course content and yourself...',
    'general.hourlyPrice': 'Lesson Price (₺/Hour)',
    'general.hours': 'Hours',
    'general.lessonDurationHours': 'Lesson Duration (Hours)',
    'general.hourlyPricePlaceholder': 'E.g.: 20',
    'general.instructorFrom': 'Instructor You Take Lessons From',
    'general.instructorFromPlaceholder': 'E.g.: Ankara University, Prof. Dr. Ahmet Yilmaz',
    'general.publishListing': 'Publish Listing',
    'general.listingCreated': 'Your listing has been created successfully!',
    'general.searchPlaceholder': 'Search listings...',
    'general.filterOptions': 'Filter Options',
    'general.sort': 'Sort',
    'general.newest': 'Newest',
    'general.oldest': 'Oldest',
    'general.priceAsc': 'Price (Ascending)',
    'general.priceDesc': 'Price (Descending)',
    'general.minPrice': 'Minimum Price (₺)',
    'general.maxPrice': 'Maximum Price (₺)',
    'general.allMethods': 'All methods',
    'general.minPricePlaceholder': 'Minimum price',
    'general.maxPricePlaceholder': 'Maximum price',
    'general.resultsFound': 'listings found',
    'general.notSpecified': 'Not Specified',
    'general.unknown': 'Unknown',
    'general.noResultsFound': 'No Search Results Found',
    'general. resourceSearchNoResults': 'Resource Not Found',
    'general.downloadStarted': 'Download started.',
    'general.downloadError': 'An error occurred during download. Please try again.',
    'general.fileNotFound': 'File not found. There is no downloadable file for this resource.',
    'general.noListingsYet': 'No Listings Yet',
    'general.listingsWillAppear': 'Listings will appear here as instructors from your university create them.',
    'general.tryAgain': 'Try Again',
    'general.listingDetails': 'Listing Details',
    'general.lessonDetails': 'Lesson Details',
    'general.teacherInfo': 'Teacher Information',
    'general.additionalInfo': 'Additional Information',
    'general.allListings': 'All Listings',
    'general.hour': 'Hour',
    'general.viewDetails': 'View Details',
    'general.locale': 'en',
    'general.currency': 'Turkish Lira',
    
    // Homepage
    'home.mainTitle': 'Find the students that best suit your needs, start learning now!',
    'home.showAllUniversities': 'Show all universities',
    'home.allUniversities': 'All Universities',
    'home.selectUniversity': 'Select your university...',
    'home.description ': 'Kavunla is a next-generation education platform that brings together students from the same university.',
    'home.exploreCourses': 'Explore Courses',
    'home.howToContinue': 'How would you like to continue?',
    'home.continueAsStudent': 'Continue as Student',
    'home.continueAsInstructor': 'Continue as Instructor',
    
    // Profile page
    'profile.profileInfo': 'Profile Information',
    'profile.editProfile': 'Edit Profile',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.university': 'University',
    'profile.role': 'Role',
    'profile.department': 'Department',
    'profile.class': 'Class',
    'profile.updateSuccess': 'Profile updated successfully.',
    'profile.accountStatus': 'Account Status',
    'profile.verified': 'Verified',
    'profile.unverified': 'Unverified',
    'profile.preparatory': 'Preparatory',
    'profile.firstYear': '1st Year',
    'profile.secondYear': '2nd Year',
    'profile.thirdYear': '3rd Year',
    'profile.fourthYear': '4th Year',
    'profile.fifthYear': '5th Year',
    'profile.sixthYear': '6th Year',
    'profile.graduate': 'Graduate',
    
    // Messages page
    'messages.myMessages': 'My Messages',
    'messages.conversations': 'My Conversations',
    'messages.startMessaging': 'Start Messaging',
    'messages.selectConversation': 'Select a conversation from the left or visit instructor profiles to start a new conversation.',
    'messages.loginRequired': 'You need to log in to view your messages',
    'messages.noMessages': 'You don\'t have any messages yet',
    'messages.visitInstructors': 'You can visit instructor profiles to start messaging with them.',
    'messages.exploreInstructors': 'Explore Instructors',
    
    // My Listings page
    'myListings.myListings': 'My Listings',
    'myListings.addNewListing': 'Add New Listing',
    'myListings.noListingsYet': 'You haven\'t created any listings yet.',
    'myListings.addYourFirstListing': 'Add Your First Listing',
    
    // Authentication pages
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.haveAccount': 'Already have an account?',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot password',
    'auth.fullName': 'Full Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.role': 'Role',
    'auth.student': 'Student',
    'auth.instructor': 'Instructor',
    'auth.university': 'University',
    'auth.selectUniversity': 'Select your university...',
    'auth.department': 'Department',
    'auth.departmentPlaceholder': 'Enter your department...',
    'auth.class': 'Class',
    'auth.selectClass': 'Select',
    'auth.passwordRequirement': 'Must be at least 8 characters',
    'auth.loggingIn': 'Logging in...',
    'auth.registering': 'Registering...',
    'auth.otherSignInOptions': 'Other sign in options',
    'auth.termsAgreement': 'By signing up, you agree to our',
    'auth.termsOfUse': 'Terms of Use',
    'auth.and': 'and',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.loginError': 'Error occurred during login',
    'auth.registrationError': 'Error occurred during registration',
    'auth.passwordsDoNotMatch': 'Passwords do not match',
    'auth.loadingUniversities': 'Error loading universities',
    'auth.loadingConversations': 'Error loading conversations',
    'auth.loadingConversationsDetail': 'An error occurred while loading conversations:',
    'auth.fetchingUserDetails': 'Error fetching user details',
    'auth.titleRequired': 'Please enter a title',
    'auth.descriptionRequired': 'Please enter a description',
    
    // My Lessons page
    'lessons.myLessons': 'My Lessons',
    'lessons.teacherManageLessons': 'You can manage all your lessons from this page.',
    'lessons.studentViewLessons': 'You can view all the lessons you are registered for from this page.',
    'lessons.totalLessons': 'Total Lessons',
    'lessons.plannedLessons': 'Planned Lessons',
    'lessons.completedLessons': 'Completed Lessons',
    'lessons.cancelledLessons': 'Cancelled Lessons',
    'lessons.lessonCalendar': 'Lesson Calendar',
    'lessons.status': 'Status',
    'lessons.start': 'Start',
    'lessons.end': 'End',
    'lessons.student': 'Student',
    'lessons.instructor': 'Instructor',
    'lessons.price': 'Price',
    'lessons.completeLesson': 'Complete Lesson',
    'lessons.cancelLesson': 'Cancel Lesson',
    'lessons.viewLessonDetails': 'View Lesson Details',
    'lessons.statusOpen': 'Open',
    'lessons.statusScheduled': 'Scheduled',
    'lessons.statusCompleted': 'Completed',
    'lessons.statusCancelled': 'Cancelled',
    'lessons.details': 'Lesson Details',
    'lessons.createdAt': 'Created At',
    'lessons.minute': 'minute',
    'lessons.noDate': 'No date specified',
    'lessons.notFound': 'Lesson Not Found',
    'lessons.notFoundDesc': 'The lesson you are trying to view was not found or you do not have access.',
    'lessons.completedAt': 'Completed',
    'lessons.studentInfo': 'Student Information',
    'lessons.teacherInfo': 'Instructor Information',
    'lessons.paymentStatus': 'Payment Status',
    'lessons.notPaid': 'Payment has not been made for this lesson yet.',
    'lessons.payNow': 'Pay Now',
    'lessons.paid': 'Payment completed',
    'messages.sendMessage': 'Send Message',
    'lessons.student ': 'Student',
    'lessons.teacher': 'Instructor',
    'general.noName': 'No name specified',
    'general.noEmail': 'No email specified',

    // Logs and errors
    'logs.userNotLoggedIn': 'User not logged in, redirecting...',
    'logs.listingCreationError': 'Error creating listing:',
    'logs.previewUpdateError': 'An error occurred while updating preview count',
    'logs.fetchingLessonStats': 'User logged in, fetching lesson statistics...',
    'logs.sendingApiRequest': 'Sending API request:',
    'logs.tokenAvailable': 'Token available:',
    'logs.lessonStatsReceived': 'Lesson statistics received:',
    'errors.userInfoNotFound': 'User information not found',
    'errors.apiError': 'API error:',
    'errors.errorDetails': 'Error details:',
    'errors.fetchingLessonStats': 'An error occurred while fetching lesson statistics',
    'errors.fetchingLessonStatsError': 'Error fetching lesson statistics:',
    'errors.serverError': 'Server error',
    'errors.universityNotFound': 'University information not found',
    'errors.fetchingListings': 'Error fetching listings',
    'errors.tokenNotFound': 'Token not found',
    'errors.sessionExpired': 'Your session appears to have expired. Please log in again.',
    'errors.unknownError': 'Unknown error',
    'errors.httpError': 'HTTP error: {status}',
    'errors.loginError': 'Error occurred during login',
    'errors.registrationError': 'Error occurred during registration',
    'errors.passwordsDoNotMatch': 'Passwords do not match',
    'errors.loadingUniversities': 'Error loading universities',
    'errors.loadingConversations': 'Error loading conversations',
    'errors.loadingConversationsDetail': 'An error occurred while loading conversations:',
    'errors.fetchingUserDetails': 'Error fetching user details',
    'errors.titleRequired': 'Please enter a title',
    'errors.descriptionRequired': 'Please enter a description',
    'errors.durationRequired': 'Please enter duration information',
    'errors.userIdNotFound': 'User ID not found. Please log in again.',
    'errors.sessionNotFound': 'Session information not found. Please log in again.',
    'errors.listingCreationError': 'An error occurred while creating the listing',
    'errors.listingCreationErrorTryAgain': 'An error occurred while creating the listing. Please try again later.',
    'errors.loginRequired': 'You need to log in to download this resource.',
    'errors.noDownloadPermission': 'You do not have permission to download this resource.',
    'errors.invalidUniversity': 'Please select a valid university',
    'errors.invalidDepartment': 'Please select a valid department',
    
    // Footer
    'footer.platformDescription': 'Kavunla is a platform that brings students together with instructors and shapes the future of education.',
    'footer.quickLinks': 'Quick Links',
    'footer.legal': 'Legal',
    'footer.termsOfUse': 'Terms of Use',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.cookiePolicy': 'Cookie Policy',
    'footer.pdpl': 'PDPL',
    'footer.contact': 'Contact',
    'footer.allRightsReserved': 'All rights reserved.',
    'footer.support': 'Support',
    'footer.security': 'Security',
    'footer.notification': 'Notification',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('tr');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'tr' || savedLanguage === 'en')) {
        setLanguage(savedLanguage);
      }
      setMounted(true);
    }
  }, []);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', language);
    }
  }, [language]);

  const t = (key: string, params?: Record<string, any>): string => {
    let translation = translations[language][key] || key;
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, params[param]);
      });
    }
    return translation;
  };

  if (!mounted) {
    return <div />;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
